### ISSUE TITLE
Eliminar los archivos generados

### ISSUE THREAD

**Issue by delucas** [edsgerdijkstraunlam/Tp-Asistente-CadenaDeResponsabilidad#1]
No se debe llevar control de los archivos generados automáticamente. En Java, es necesario compilar los fuentes para ejecutarlos. Sin embargo, esa compilación no sirve al proyecto en sí mismo.
Lo único que deberían dejar, es el código y la configuración. Quizás imágenes, pero nunca los archivos que se generan automáticamente.
Eliminar `bin` y agregarlo a `.gitignore`.

**Comment by davidblanco117** [comment]
bin ya no forma parte de las carpetas en github y está agregado al .gitignore
