### ISSUE TITLE
¿Es el mismo test dos veces?

### ISSUE THREAD

**Issue by delucas** [edsgerdijkstraunlam/Tp-Asistente-CadenaDeResponsabilidad#3]
https://github.com/edsgerdijkstraunlam/Tp-Asistente-CadenaDeResponsabilidad/blob/f1a4b41c38bb7104f18828db3bb53650f4d2ef8e/src/Test/LeyesDeLaRoboticaTest.java#L22

**Comment by davidblanco117** [comment]
Se cambia el test repetido por otro
