### ISSUE TITLE
Eliminar comentarios innecesarios

### ISSUE THREAD

**Issue by delucas** [edsgerdijkstraunlam/Tp-Asistente-CadenaDeResponsabilidad#4]
Por ejemplo este, pero no me refiero sólamente a este:

https://github.com/edsgerdijkstraunlam/Tp-Asistente-CadenaDeResponsabilidad/blob/f1a4b41c38bb7104f18828db3bb53650f4d2ef8e/src/cadenaDeResponsabilidades/FechayHora.java#L178

**Comment by davidblanco117** [comment]
Comentarios innecesarios borrados
