### ISSUE TITLE
Métodos públicos

### ISSUE THREAD

**Issue by delucas** [edsgerdijkstraunlam/Tp-Asistente-CadenaDeResponsabilidad#5]
Esta clase tiene demasiados métodos públicos. Revisar si no fue un error, y simplemente son privados (accesibles sólamente para la responsabilidad de la cadena, y no para toda la cadena).

https://github.com/edsgerdijkstraunlam/Tp-Asistente-CadenaDeResponsabilidad/blob/f1a4b41c38bb7104f18828db3bb53650f4d2ef8e/src/cadenaDeResponsabilidades/FechayHora.java#L13

**Comment by davidblanco117** [comment]
Se cambian varios métodos públicos de la clase fechaYHora a private
