### ISSUE TITLE
Jerarquía de CoR

### ISSUE THREAD

**Issue by delucas** [edsgerdijkstraunlam/Tp-Asistente-CadenaDeResponsabilidad#7]
Asignar el siguiente, y seguirlo, son métodos que deben resolverse al nivel más alto de la jerarquía.

https://github.com/edsgerdijkstraunlam/Tp-Asistente-CadenaDeResponsabilidad/blob/f1a4b41c38bb7104f18828db3bb53650f4d2ef8e/src/cadenaDeResponsabilidades/Agradecimiento.java#L36

**Comment by davidblanco117** [comment]
Se cambio la interfaz ReceptorDeMensaje a una clase abstracta y se implementaron los métodos setNext() y getNext() ahí.
